### ISSUE TITLE
Remove need for .fontface class in <html> element

### ISSUE THREAD

**Issue by 4ndr01d3** [ebiwd/EBI-Icon-fonts#3]
When I was trying to use this repo I noticed it requires that the html element has the fontface class, which I believe is added by modernizr, however we are not using  it modernizr, and think this there is unnecessary, among other things because font face is supported by all the major browsers. 

I know from our side is as simple as adding that class into the html, but I thought of mention it as it can create issues for those that want to use this repo. At last it should be mention in the Readme.

Thanks,
Gustavo.

**Comment by khawkins98** [comment]
Good point.

The current implementation was devised back in 2012 and constructed with IE7 fallbacks in mind. 

I'm thinking we should make the releases of this tie in with the main [EBI Visual framework](http://github.com/ebiwd/EBI-Framework). So that would mean we're due for a 0.1 update every 6 months.

**Comment by 4ndr01d3** [comment]
That's a good idea! I'll keep an eye for future versions.

**Comment by khawkins98** [comment]
This was done in v1.2, closing.
